
# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /
  Archives: /archives
  联系我: mailto:2228598786@qq.com
  Codes: https://github.com/Benjmmi/Benjmmi.github.io/tree/main/assets/codes

# Social
social:
  email: 2228598786@qq.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/Benjmmi/Benjmmi.github.io
  weibo:
  douban:
  zhihu:
  pocket:
  tumblr:
  instagram:

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/iLiKE.css

# scripts loaded in the end of the body
scripts:
- /js/iLiKE.js

# Site creation time
since: 2017

# Blog auto_excerpt
auto_excerpt:
  enable: true
  length: 150


# ===========================================
# Third Party Services Settings
# ===========================================
